Paitent_Manager_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinic/', include('clinic.urls')),
	re_path(r'^nested_admin/', include('nested_admin.urls')),
]

clinic/urls.py
from django.urls import path, re_path
from . import views
from . import test
app_name = 'clinic'
handler404 = 'clinic.views.handler404'

urlpatterns = [
    # re_path(r'$', views.er_404, name='er_404'),
    path('', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
	path('add/<str:model>', views.add, name="add"),
    path('view/<str:model>/<int:pk>', views.view, name='view'),
    # path('test',test.a,name='test'),
    # # path('<str:object>/<str:pk>/', views.view_object, name='view'),
]

clinic/forms.py
from django import forms

from clinic.models import *
from clinic.utils.log import Logger

import clinic.utils.validators as v

logger = Logger()

class LoginForm(forms.Form):
	username = forms.CharField(validators=[v.validate_username_login])
	password = forms.CharField()

	def clean(self):
		cleaned_data = super().clean()
		username = cleaned_data.get('username')
		password = cleaned_data.get('password')
		if (username):
			d = Doctor.objects.get(pk=username)
			# Checking Password
			if not d.verify_password(password):
				self.add_error('password', 'Wrong password!')
		return cleaned_data

class AddressForm(forms.ModelForm):
	class Meta:
		model = Address
		fields = '__all__'

class PhoneForm(forms.ModelForm):
	class Meta:
		model = Phone
		fields = '__all__'

class PatientForm(forms.ModelForm):
	class Meta:
		model = Patient
		exclude = ['reg_time', 'clinic', ]

class EmergencyContactForm(forms.ModelForm):
	class Meta:
		model = EmergencyContact
		exclude = ['person', ]


class PatientFormSet:

	def __init__(self, data={}, clinic=None):
		self.data = data
		self.clinic = clinic
		logger.d("data:", data)
		if not isinstance(data, dict):
			raise Exception("Data should be of type dictonary and not" + str(type(data)))
		self.patient = PatientForm(data)
		self.address = AddressForm(data)
		self.emergency_contact = EmergencyContactForm(data)
		self.er_phones = [PhoneForm({'phone_number' : data['er_phone_number'], 'type': ['er_type']} if 'er_phone_number' in data else data), ]
		self.phones = [PhoneForm(data), ]
		if data:
			i = 1
			while 'phone_number-' + str(i) in data:
				phone_number = data['phone_number-' + str(i)]
				type = data['type-' + str(i)]
				p = PhoneForm({'phone_number' : phone_number, 'type' : type, })
				self.phones.append(p)
				i = i + 1
				er_phones =[]
			i = 0
			while 'er_phone_number-' + str(i) in data:
				phone_number = data['er_phone_number-' + str(i)]
				type = data['er_type-' + str(i)]
				p = PhoneForm({'phone_number': phone_number, 'type': type, })
				p.index = i
				self.er_phones.append(p)
				i = i + 1

	def get_fields(self):
		return [self.patient, self.address, self.phones, self.emergency_contact, self.er_phones];

	def get_models_all(self):
		return [self.patient, self.address, self.emergency_contact, ] + self.phones #+ self.er_phones

	def is_valid(self):
		b = True;
		for form in self.get_models_all():
			b = b and form.is_valid()
			if not b: return b
		return b

	def get_form_as_p(self):
		return "".join([form.as_p() for form in self.get_models_all()])

	def get_form_as_table(self):
		return "".join([form.as_table() for form in self.get_models_all()])

	def get_form_as_li(self):
		return "".join([form.as_li() for form in self.get_models_all()])

	def get_errors(self):
		l = [form.errors for form in self.get_models_all() if not form.is_valid()]
		logger.d(l)
		er = {}
		for i in l:
			er = {**er, **i}
		return er

	def save(self):
		if not self.is_valid():
			raise Exception("Form is not valid!\n" + self.get_errors())
		patient = self.patient.save(commit=False)
		patient.clinic = self.clinic
		patient.save()
		person = patient.person_ptr
		address = self.address.save()
		er_cont =  self.emergency_contact.save(commit=False)
		er_cont.person = person
		er_cont.save()
		d = PersonAddress(person=person, address=address).save();
		# logger.d("PersonAddress:", d, "Address:",address)

		for phone in self.phones:
			phone = phone.save()
			PersonPhone(person=patient.person_ptr, phone_number=phone).save()

		for er_phone in self.er_phones:
			phone = er_phone.save()
			EmergencyContactPhone(er_phone_number=phone, emergency_contact=er_cont).save()
		return patient

	def __str__(self):
		return self.get_form_as_p()

# from django.forms.models import formset_factory, inlineformset_factory, BaseInlineFormSet
# from django.core.exceptions import ObjectDoesNotExist
# from django.contrib.admin.widgets import AdminDateWidget, ForeignKeyRawIdWidget
# from django.core.exceptions import ObjectDoesNotExist
# from django.db.models.fields.reverse_related import ManyToOneRel
# from django.db.models.fields.related import OneToOneField
# from django.db.models.fields import AutoField
# import clinic.utils.constants as consts

# P_PhoneFormSet = inlineformset_factory(PersonPhone, Phone, fields='__all__', extra=1)
# P_AddressFormSet = inlineformset_factory(PersonAddress, Address, fields='__all__', extra = 1)
#
# class BasePersonPhoneFormSet(BaseInlineFormSet):
#
# 	def add_fields(self, form, index):
# 		super(BasePersonPhoneFormSet, self).add_fields(form, index)
#
# 		form.nested = P_PhoneFormSet(
# 						instance=form.instance,
# 						data=form.data if form.is_bound else None,
# 						files=form.files if form.is_bound else None,
# 						prefix='Phone-%s-%s' % (form.prefix, P_PhoneFormSet.get_default_prefix()),
# 						extra=1)
#
#
# class BasePersonAddressFormSet(BaseInlineFormSet):
#
# 	def add_fields(self, form, index):
# 		super(BasePersonAddressFormSet, self).add_fields(form, index)
#
# 		form.nested = P_AddressFormSet(
# 						instance=form.instance,
# 						data=form.data if form.is_bound else None,
# 						files=form.files if form.is_bound else None,
# 						prefix='Address-%s-%s' % (form.prefix, P_AddressFormSet.get_default_prefix()),
# 						extra=1)
#
# PersonPhoneFormSet = inlineformset_factory(Person, PersonPhone, fields='__all__', \
# 											 formset=BasePersonPhoneFormSet, extra=1)
#
# PersonAddressFormSet = inlineformset_factory(Person, PersonAddress, fields='__all__', \
# 											 formset=BasePersonAddressFormSet, extra=1)

# class PersonForm(SuperModelForm):
# 	phone = ModelFormField(form_class=PersonPhoneForm)
# 	address = ModelFormField(form_class=PersonAddressForm)
#
# 	class Meta:
# 		model = Person
# 		exclude = ['id', 'reg_time']
#
# class PatientForm(SuperModelForm):
# 	phone = InlineFormSetField(formset_class=PersonPhoneFormSet)
# 	address = InlineFormSetField(formset_class=PersonAddressFormSet)
#
# 	def __init__(self, clinic=None, *arg, **kwargs):
# 		super().__init__(*arg, **kwargs)
# 		self.clinic = clinic
#
# 	class Meta:
# 		model = Patient
# 		exclude = ['id', 'reg_time', 'clinic']


# def getValue(self, field):
#     return self[field].value()
#
# exceptions = [ManyToOneRel, AutoField, OneToOneField]
#
# def save_object(self, object_class, to_commit, *exclude, **extra):
#     fields = object_class._meta.get_fields()
#     attrs = [x.attname for x in fields if (type(x) not in exceptions and x.attname not in exclude)]
#     values = {x : getValue(self, x) for x in attrs}
#     values = {**values, **extra}
#     obj = object_class(**values)
#     if to_commit: obj.save()
#     return obj;
# class AddressForm(forms.Form):
#
#     class Meta:
#         model = Address
#         exclude = ['id']
# class GenericForm(forms.ModelForm):
#     # TODO: fix profile field not saving
#
#     class Meta:
#         model = Person
#         exclude = ['reg_time', 'id']
# class DoctorForm(LoginForm, GenericForm):
#     username = forms.CharField(validators=[v.validate_username_create])
#     confirm_pass = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
#
#     speciality  = forms.ChoiceField(choices=consts.specialties, initial='gp')
#     qual = forms.CharField(label='Qualification', max_length=20, required=False)
#     bio = forms.CharField(label='Biography', required=False)
#
#     def __str__(self):
#         return getValue(self, 'username')
#
#     def save(self, commit=True):
#         if not self.is_valid():
#             raise Exception('The form has invalid fields' + str(self.errors))
#
#         if not getValue(self, 'password') == getValue(self, 'confirm_pass'):
#             ex = Exception('Passwords doesn\'t match!')
#             ex.data = {'confirm_pass' : 'Passwords doesn\'t match!'}
#             raise ex
#
#         return save_object(self, Doctor, commit, 'reg_time', 'id')
# class PatientForm(GenericForm, forms.ModelForm):
#     class Meta:
#         model = Patient
#         exclude = ['reg_time', 'id', 'registered_by_id', 'registered_by']
#
#     def save(self, doctor, commit=True):
#         return save_object(self, Patient, commit, *self.Meta.exclude, registered_by=doctor)
#
#     def __str__(self):
#         return getValue(self, 'first_name') + getValue(self, 'last_name')
# class CaseForm(forms.ModelForm):
#
#     class Meta:
#         model = Patient
#         exclude = []
#
#     def __str__(self):
#         return 'Case'
#
# class ApptForm(forms.ModelForm):
#     class Meta:
#         model = Appointment
#         exclude = []
#
#     def __str__(self):
#         return 'Appointment'

clinic/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist

from clinic.forms import *
from clinic.models import *
from clinic.utils import log, utilities
<<<<<<< HEAD
=======
from clinic.forms import *
>>>>>>> 5ab21846fc6691c11e626fe83a36c178362f9805

logger = log.Logger()

def get_user(request):
	return Doctor.objects.get(pk=request.session['doctor_id'])

def index(request):
	context, page = {'model_doctor' : Doctor, }, 'index.html'
	if 'doctor_id' in request.session:
		try:
			doctor = get_user(request)
			context['doctor'] = doctor
			if 'clinic_id' in request.session:
				clinic = Clinic.objects.get(pk=request.session['clinic_id'])
				context["clinic_head"] = True
				context['branch'] = clinic.branch_set.get(pk=request.session['branch_id'])
				context['branches'] = list(clinic.branch_set.all())
				context['branches'].remove(context['branch'])
			elif 'branch_id' in request.session:
				context['branch'] = Branch.objects.get(pk=request.session['branch_id'])
		except (ObjectDoesNotExist) as ex:
			logger.w(ex)
			return logout(request)
	else:
		page = "login.html"
		if request.method == 'POST':
			form = LoginForm(request.POST)
			if form.is_valid():
				username = request.POST['username']
				d = Doctor.objects.get(pk=username)
				try:
					clinic = d.clinic
					request.session['clinic_id'] = clinic.pk
					try:
						request.session['branch_id'] = d.branch.pk
					except ObjectDoesNotExist as e:
 						request.session['branch_id'] = clinic.branch_set.all()[0].pk
				except ObjectDoesNotExist as ex:
					try:
						request.session['branch_id'] = d.branch.pk
					except ObjectDoesNotExist as e:
						try:
							request.session['branch_id'] = d.branchassistantdoctor.branch.pk
						except Exception as e:
							# TODO: add_cookie to show error
							context['ermsg'] = "Username '" + username + "' doesn't have branch associated with it contact Database administrative"
							logger.w(e, "Username '" + username + "' doesn't have branch associated with it contact Database administrative")
							return render(request, 'clinic/' + page, context)
				request.session['doctor_id'] = username
				return redirect('/clinic')
			else:
				context['extra'] = {'values' : form.data , 'errors' : dict(form.errors)}
	return render(request, 'clinic/' + page, context)

def logout(request):
	try:
		del request.session['doctor_id']
	except KeyError: pass
	return redirect('/clinic')

def add_patient(request):
	d, clinic = None, None
	try:
		d = get_user(request)
		if 'clinic_id' in request.session:
			clinic = Clinic.objects.get(pk=request.session['clinic_id'])
		elif 'branch_id' in request.session:
			clinic = branch.objects.get(pk=request.session['branch_id']).clinic
		else: clinic = d.branchassistantdoctor.branch.clinic
	except Exception as e:
		logger.e(e, "views.py > add_patinet: Getting Patient Failed");
		raise e
		# return logout(request)
	form = PatientFormSet(request.POST, clinic)
	context = {'doctor' : d, "form" : form.get_form_as_table(), }

	if request.method == "POST":
		if form.is_valid:
			p = form.save()
			return redirect('/clinic/view/patient/' + str(p.pk))
		else:
			context['extra'] = {'data' : None, 'errors' : dict(forms.get_errors()), }
	else:
		pass
	return render(request, 'clinic/new-patient.html', context)

add_functions = {
	'patient' : add_patient
}

def add(request, model):
	return add_functions[model](request)

def view(request, model, pk):
	# TODO: AddView For viewing models
	raise Http404

# models = {'doctor' : Doctor,
# 		  'patient' : Patient,
# 		  'case' : Case,
# 		  'appt' : CaseAppointment, }

#
# def index(request):
# 	d = get_user(request)
# 	logger.d(type(d))
# 	if(isinstance(d, Exception)):
# 		err = 'Session Experied!'
# 		if(isinstance(d, ObjectDoesNotExist)):
# 			err = 'Login Required'
# 		response = redirect('login/');
# 		response.set_cookie('error', err, 5)
# 		return response
# 	return render(request, 'clinic/index.html', {'doctor': d})
#
#

# # def view_object(request, object, pk):
# #     objects = []
# #     try:
# #         doctor = Doctor.objects.get(pk=request.session['current_user'])
# #         context = {'doctor' : doctor, 'pk' : pk, 'obj' : object, }
# #     except Exception as e:
# #         return redirect('/clinic/')
# #     if not object in models.keys():
# #         raise Http404
# #     model = models[object]
# #     if pk == 'all':
# #         objects = list(getattr(doctor, object + '_set').all());
# #     else:
# #         object = get_object_or_404(model, pk=int(pk))
# #         objects.append(object)
# #     context['objects'] = objects
# #     return render(request, 'clinic/view.html', context)
#
# def add_doctor(request):
# 	context = dict()
# 	form = DoctorForm()
# 	if request.method == 'POST':
# 		form = DoctorForm(request.POST)
# 		logger.d.d('Post Data:\n', request.POST)
# 		if form.is_valid():
# 			try:
# 				doctor = form.save()
# 			except Exception as e:
# 				context['extra'] = { 'errors': e.data, 'values' : form.data, }
# 			else:
# 				return redirect('/clinic/')
# 		else:
# 			context['extra'] = {'errors' : dict(form.errors), 'form' : form, 'values' : form.data, }
# 	context['object'] = Doctor
# 	context['address'] = Address
# 	return render(request, 'clinic/new-doctor.html', context)
#
# def add_patient(request):
# 	try:
# 		context = {'doctor' :  Doctor.objects.get(pk=request.session['current_user']) }
# 	except Exception as e:
# 		return redirect('/clinic/')
# 	if request.method == 'POST':
# 		form = PatientForm(request.POST)
# 		if form.is_valid():
# 			try:
# 				patient = form.save(context['doctor_id'])
# 			except Exception as e:
# 				context['extra'] = {'errors': e.data, 'values' : form.data, }
# 			else:
# 				# TODO: add success msg
# 				return redirect('/clinic/')
# 		else:
# 			context['extra'] = {'errors': dict(form.errors), 'form' : form, 'values' : form.data, }
# 	context['object'] = Patient
#
# 	return render(request, 'clinic/new-patient.html', context)
#
# def add_case(request):
# 	p = validate_user(request)
# 	if(p is not None):
# 		return p
#
# create_func = {'doctor' : add_doctor, 'patient': add_patient,
# 				'case' : add_case, }
#
# def add_object(request, object):
# 	if object in create_func.keys():
# 		return create_func[object](request)
# 	raise Http404
# #
# #
# # def handler404(request, *args, **argv):
# #     response = render_to_response('404.html', {}, context_instance=RequestContext(request))
# #     response.status_code = 404
# #     return response

clinic/templates/clinic/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
	<meta charset="utf-8">
	<meta name="author" content="Pranav Raut">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link type="text/css" rel="stylesheet" href="{% static 'clinic/css/master.css' %}" media="screen,projection" />
	<link href="https://fonts.googleapis.com/css?family=Baloo+Paaji|Cutive+Mono|Varela+Round&amp;subset=hebrew" rel="stylesheet">
	<title>{% block title %} {% endblock %}</title>
	{% block head %} {% endblock %}
</head>

<body {% block body_ots %} {% endblock %} class="bg-light">
	{% block body %} {% endblock %}
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script type="text/javascript" src="{% static 'clinic/js/popper.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'clinic/js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'clinic/js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'clinic/js/master.js' %}"></script>
</body>

</html>

clinic/templates/clinic/base_extra.html
{% extends 'clinic/base.html' %}
{% load static %}
{% block body %}
{% include "clinic/includes/header.html" %}
{% block content %}
{% endblock %}
{% include "clinic/includes/footer.html" %}
{% endblock %}

clinic/templates/clinic/index.html
{% extends 'clinic/base_extra.html' %}
{% load static %}
{% load view-helper %}
{% block title %} {{ doctor }} | Clinic {% endblock %}
{% block body_ots %} id="one-page" {% endblock%}
{% block body %}
{% include "clinic/includes/header.html" %}
<div class="container content-main">
	<div class="row">
		<div class="col-12 col-md-9">
			<div class="calender">Calender</div><hr>
			<div class="row">
				<div>
					<ul>
						 <li><a href="{% url 'clinic:add' 'patient' %}">Add Patient</a></li>
					 	{# <li><a href="{% url 'clinic:view' 'patient' 'all'%}">View All Patient</a> #} 
					</ul>
				</div>
			</div>
		</div>
		<div id="side-bar" class="col-12 col-md-3">
			{% sub_menu_e "Upcoming" %}
			{% sub_menu_e "Recents" %}
		</div>
	</div>
</div>
{% include "clinic/includes/footer.html" %}
{% endblock %}

clinic/templates/clinic/license.html
<div><b>Doctor male and female</b><br>Icons made by <a href="https://www.flaticon.com/authors/vectors-market" title="Vectors Market">Vectors Market</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
<hr>
<div><b>User Avatar:</b><br>Icons made by <a href="https://www.flaticon.com/authors/gregor-cresnar" title="Gregor Cresnar">Gregor Cresnar</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

clinic/templates/clinic/login.html
{% extends 'clinic/base_extra.html' %}
{% load static %}
{% block title %} Login | Clinic {% endblock %}
{% load view-helper %}
{% block body_ots %} id="one-page" {% endblock %}
{% block content %}
<div class="container content-main">
	<div class="row align-items-center">
		<div class="col-12 col-md-5 promotion-block">
			<h2 class="title">Welcome, Doctor</h2><hr>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>
		<div class="col-12 offset-md-1 col-md-5 align-middle">
			{% if ermsg %}
			<div class="alert alert-danger alert-dismissiable fade show rounded" data-toggle="tooltip" data-placement="top" title="Click to dismiss">
				<span data-dismiss="alert">{{ ermsg }}</span>
			</div>
			{% endif %}
			<div class="card border-primary">
				<div class="card-header">
					<h2 class="card-title text-primary m-0">Clinic <small class="text-muted">login</small></h2>
				</div>
				<div class="card-body">
					<form if="form" method="post">
						{% csrf_token %}
						{% input model_doctor 'username' 'col-auto' icon='face' extra=extra options='pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$" title="Invalid Username format"'%}
						{% input model_doctor 'password' 'col-auto' 'password' icon='vpn_key' extra=extra %}
						<div class="text-right">
							<button type="submit" class="card-link btn btn-primary">Login</button>
							{# <a href="{% url 'clinic:add' 'doctor'%}" class="card-link">New Doctor?</a> #}
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="col-0 col-md-1 d-none d-sm-flex" style="height:85vh; width: 1px;"></div>
	</div>
</div>
{% endblock %}

clinic/templates/clinic/new-doctor.html
{% extends "clinic/base_extra.html" %}
{% load view-helper %}
{% block title %}Add Doctor| Clinic{% endblock %}
{% block head %} 
	<script type="text/javascript">
		function limitLength(t, limit) {
			if (t.value.length > limit)
				t.value = t.value.slice(0, limit);
		}
	</script> 
{% endblock %}
{% block content %}
	<div class="container py-4">
		<div class="row">
			<div class="col-12 col-lg-7 mx-auto">
				<div class="card border-primary">
					<div class="card-header">
						<h3 class="card-title m-0">New <small class="text-muted">Doctor</small></h3>
					</div>
					<div class="card-body">
						<form method="post" id="doctor_form" action="{% url 'clinic:add' 'doctor'%}" enctype="multipart/form-data">
							{% csrf_token %}
							<fieldset>
								<legend class="text-primary">Login information</legend>
								<div class="form-row"> {% file object 'profile' label="Profile image" accept='image/*' icon='face' extra=extra %}
									{% input object 'username' icon='face' extra=extra %}
									{% input object 'password' 'col-md-6' 'password' icon='vpn_key' extra=extra %}
									{% input object 'password' 'col-md-6' 'password' id="confirm_pass" icon='vpn_key' label="Confirm Password" required=true extra=extra %} </div>
							</fieldset>
							<fieldset>
								<legend class="text-primary">Personal information</legend>
								<div class="form-row"> {% input object 'first_name' 'col-md-4' extra=extra %}
									{% input object 'middle_name' 'col-md-4' extra=extra %}
									{% input object 'last_name' 'col-md-4' extra=extra %}
									
									{% input object 'phone_number' 'col-md-5' 'tel' options='onkeypress="limitLength(this, 10)"' extra=extra %}
									{% input object 'email' 'col-md-7' 'email' extra=extra %}
									
									{% input object 'qual' 'col-md-5' 'text' icon='work' i_opts='prefix' extra=extra options="maxlength='20' onkeyup='limitLength(this, 20)'" %}
									{% select object 'speciality' 'col-md-7' icon='star' i_opts='prefix' extra=extra %} </div>
							</fieldset>
							<fieldset>
								<legend class="text-primary">Extra information</legend>
								<div class="form-row"> {% select object 'gender' 'col-md-3' extra=extra %}
									{% select object 'blood_type' 'col-md-3' extra=extra %}
									{% input object 'dob' 'col-md-6' 'date' extra=extra %}
									
									{% input address 's_address' 'col-sm-12 col-md-9' extra=extra %}
									{% input address 'pincode' 'col-sm-3' 'tel' extra=extra %}
									{% input address 'city' 'col-sm-5 col-md-3' extra=extra %}
									{% select address 'state' 'col-sm-4' extra=extra %}
									{% select address 'country' 'col-md-5' extra=extra %}
									
									{% textarea object 'bio' 250 'col-md-12' icon='info' i_opts='prefix' extra=extra %} </div>
							</fieldset>
							<input type="reset" name="reset" value="Clear" class="card-link btn btn-light">
							<div class="float-right"> <a class="card-link" onclick="javascript:history.go(-1)">Cancel</a>
								<button type="submit" class="card-link btn btn-primary" value="{{ next }}">Create</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %} 

clinic/templates/clinic/new-patient.html
{% extends "clinic/base_extra.html" %}
{% load utilities %}
{% load view-helper %}
{% load static %}
{% block title %}New Patient | {{ doctor.name }}{% endblock %}
{% block content %}
{% if form %}
	{% set width = "col-lg-9" %}
	{% set file_field_w = "col-sm-9" %}
{% else %}
	{% set width = "col-lg-7" %}
{% endif %}
<div class="container py-4">
	<div class="row">
		<div class="col-12 {{width}} mx-auto">
			<div class="card border-primary">
				<div class="card-header">
					<h3 class="card-title text-dark m-0">Register <small class="text-muted">Patient</small></h3>
				</div>
				<div class="card-body">
					<form class="form" action="{% url 'clinic:add' 'patient' %}" method="post">
						<table>
							{% csrf_token %}
							{% autoescape off %}
								{{ form}}
							{% endautoescape %}
						</table>
						<input type="submit" name="" value="">
					</form>
		        </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

clinic/templates/clinic/view.html
{% extends "clinic/base_extra.html" %}
{% load utilities %}
{% block title %}
    {%title obj %}-{%title pk %} | {{doctor}}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% ifequal objects|length 1 %}

            {% else %}
            <ul>
                {% for object in objects %}
                    <li><a href="{% url 'clinic:view' obj object.id %}">{{ object }}</a></li>
                {% endfor %}
            </ul>
            {% endifequal %}
        </div>
    </div>
{% endblock %}