Paitent_Manager_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinic/', include('clinic.urls')),
	re_path(r'^nested_admin/', include('nested_admin.urls')),
]

clinic/urls.py
from django.urls import path, re_path
from . import views
from . import test
app_name = 'clinic'
handler404 = 'clinic.views.handler404'

urlpatterns = [
    # re_path(r'$', views.er_404, name='er_404'),
    path('', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
	path('add/<str:model>', views.add, name="add"),
    path('view/<str:model>/<int:pk>', views.view, name='view'),
    # path('test',test.a,name='test'),
    # # path('<str:object>/<str:pk>/', views.view_object, name='view'),
]

clinic/forms.py
from django import forms

from clinic.models import *
from clinic.utils.log import Logger

import clinic.utils.validators as v

logger = Logger()

class LoginForm(forms.Form):
	username = forms.CharField(validators=[v.validate_username_login])
	password = forms.CharField()

	def clean(self):
		cleaned_data = super().clean()
		username = cleaned_data.get('username')
		password = cleaned_data.get('password')
		if (username):
			d = Doctor.objects.get(pk=username)
			# Checking Password
			if not d.verify_password(password):
				self.add_error('password', 'Wrong password!')
		return cleaned_data

class AddressForm(forms.ModelForm):
	class Meta:
		model = Address
		fields = '__all__'

class PhoneForm(forms.ModelForm):
	class Meta:
		model = Phone
		fields = '__all__'

class PatientForm(forms.ModelForm):
	class Meta:
		model = Patient
		exclude = ['reg_time', 'clinic', ]

class EmergencyContactForm(forms.ModelForm):
	class Meta:
		model = EmergencyContact
		exclude = ['person', ]


class PatientFormSet:

	def __init__(self, data={}, clinic=None):
		self.data = data
		self.clinic = clinic
		logger.d("data:", data)
		if not isinstance(data, dict):
			raise Exception("Data should be of type dictonary and not" + str(type(data)))
		self.patient = PatientForm(data)
		self.address = AddressForm(data)
		self.emergency_contact = EmergencyContactForm(data)
		self.er_phones = [PhoneForm({'phone_number' : data['er_phone_number'], 'type': ['er_type']} if 'er_phone_number' in data else data), ]
		self.phones = [PhoneForm(data), ]
		if data:
			i = 1
			while 'phone_number-' + str(i) in data:
				phone_number = data['phone_number-' + str(i)]
				type = data['type-' + str(i)]
				p = PhoneForm({'phone_number' : phone_number, 'type' : type, })
				self.phones.append(p)
				i = i + 1
				er_phones =[]
			i = 0
			while 'er_phone_number-' + str(i) in data:
				phone_number = data['er_phone_number-' + str(i)]
				type = data['er_type-' + str(i)]
				p = PhoneForm({'phone_number': phone_number, 'type': type, })
				p.index = i
				self.er_phones.append(p)
				i = i + 1

	def get_fields(self):
		return [self.patient, self.address, self.phones, self.emergency_contact, self.er_phones];

	def get_models_all(self):
		return [self.patient, self.address, self.emergency_contact, ] + self.phones #+ self.er_phones

	def is_valid(self):
		b = True;
		for form in self.get_models_all():
			b = b and form.is_valid()
			if not b: return b
		return b

	def get_form_as_p(self):
		return "".join([form.as_p() for form in self.get_models_all()])

	def get_form_as_table(self):
		return "".join([form.as_table() for form in self.get_models_all()])

	def get_form_as_li(self):
		return "".join([form.as_li() for form in self.get_models_all()])

	def get_errors(self):
		l = [form.errors for form in self.get_models_all() if not form.is_valid()]
		logger.d(l)
		er = {}
		for i in l:
			er = {**er, **i}
		return er

	def save(self):
		if not self.is_valid():
			raise Exception("Form is not valid!\n" + self.get_errors())
		patient = self.patient.save(commit=False)
		patient.clinic = self.clinic
		patient.save()
		person = patient.person_ptr
		address = self.address.save()
		er_cont =  self.emergency_contact.save(commit=False)
		er_cont.person = person
		er_cont.save()
		d = PersonAddress(person=person, address=address).save();
		# logger.d("PersonAddress:", d, "Address:",address)

		for phone in self.phones:
			phone = phone.save()
			PersonPhone(person=patient.person_ptr, phone_number=phone).save()

		for er_phone in self.er_phones:
			phone = er_phone.save()
			EmergencyContactPhone(er_phone_number=phone, emergency_contact=er_cont).save()
		return patient

	def __str__(self):
		return self.get_form_as_p()

# from django.forms.models import formset_factory, inlineformset_factory, BaseInlineFormSet
# from django.core.exceptions import ObjectDoesNotExist
# from django.contrib.admin.widgets import AdminDateWidget, ForeignKeyRawIdWidget
# from django.core.exceptions import ObjectDoesNotExist
# from django.db.models.fields.reverse_related import ManyToOneRel
# from django.db.models.fields.related import OneToOneField
# from django.db.models.fields import AutoField
# import clinic.utils.constants as consts

# P_PhoneFormSet = inlineformset_factory(PersonPhone, Phone, fields='__all__', extra=1)
# P_AddressFormSet = inlineformset_factory(PersonAddress, Address, fields='__all__', extra = 1)
#
# class BasePersonPhoneFormSet(BaseInlineFormSet):
#
# 	def add_fields(self, form, index):
# 		super(BasePersonPhoneFormSet, self).add_fields(form, index)
#
# 		form.nested = P_PhoneFormSet(
# 						instance=form.instance,
# 						data=form.data if form.is_bound else None,
# 						files=form.files if form.is_bound else None,
# 						prefix='Phone-%s-%s' % (form.prefix, P_PhoneFormSet.get_default_prefix()),
# 						extra=1)
#
#
# class BasePersonAddressFormSet(BaseInlineFormSet):
#
# 	def add_fields(self, form, index):
# 		super(BasePersonAddressFormSet, self).add_fields(form, index)
#
# 		form.nested = P_AddressFormSet(
# 						instance=form.instance,
# 						data=form.data if form.is_bound else None,
# 						files=form.files if form.is_bound else None,
# 						prefix='Address-%s-%s' % (form.prefix, P_AddressFormSet.get_default_prefix()),
# 						extra=1)
#
# PersonPhoneFormSet = inlineformset_factory(Person, PersonPhone, fields='__all__', \
# 											 formset=BasePersonPhoneFormSet, extra=1)
#
# PersonAddressFormSet = inlineformset_factory(Person, PersonAddress, fields='__all__', \
# 											 formset=BasePersonAddressFormSet, extra=1)

# class PersonForm(SuperModelForm):
# 	phone = ModelFormField(form_class=PersonPhoneForm)
# 	address = ModelFormField(form_class=PersonAddressForm)
#
# 	class Meta:
# 		model = Person
# 		exclude = ['id', 'reg_time']
#
# class PatientForm(SuperModelForm):
# 	phone = InlineFormSetField(formset_class=PersonPhoneFormSet)
# 	address = InlineFormSetField(formset_class=PersonAddressFormSet)
#
# 	def __init__(self, clinic=None, *arg, **kwargs):
# 		super().__init__(*arg, **kwargs)
# 		self.clinic = clinic
#
# 	class Meta:
# 		model = Patient
# 		exclude = ['id', 'reg_time', 'clinic']


# def getValue(self, field):
#     return self[field].value()
#
# exceptions = [ManyToOneRel, AutoField, OneToOneField]
#
# def save_object(self, object_class, to_commit, *exclude, **extra):
#     fields = object_class._meta.get_fields()
#     attrs = [x.attname for x in fields if (type(x) not in exceptions and x.attname not in exclude)]
#     values = {x : getValue(self, x) for x in attrs}
#     values = {**values, **extra}
#     obj = object_class(**values)
#     if to_commit: obj.save()
#     return obj;
# class AddressForm(forms.Form):
#
#     class Meta:
#         model = Address
#         exclude = ['id']
# class GenericForm(forms.ModelForm):
#     # TODO: fix profile field not saving
#
#     class Meta:
#         model = Person
#         exclude = ['reg_time', 'id']
# class DoctorForm(LoginForm, GenericForm):
#     username = forms.CharField(validators=[v.validate_username_create])
#     confirm_pass = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
#
#     speciality  = forms.ChoiceField(choices=consts.specialties, initial='gp')
#     qual = forms.CharField(label='Qualification', max_length=20, required=False)
#     bio = forms.CharField(label='Biography', required=False)
#
#     def __str__(self):
#         return getValue(self, 'username')
#
#     def save(self, commit=True):
#         if not self.is_valid():
#             raise Exception('The form has invalid fields' + str(self.errors))
#
#         if not getValue(self, 'password') == getValue(self, 'confirm_pass'):
#             ex = Exception('Passwords doesn\'t match!')
#             ex.data = {'confirm_pass' : 'Passwords doesn\'t match!'}
#             raise ex
#
#         return save_object(self, Doctor, commit, 'reg_time', 'id')
# class PatientForm(GenericForm, forms.ModelForm):
#     class Meta:
#         model = Patient
#         exclude = ['reg_time', 'id', 'registered_by_id', 'registered_by']
#
#     def save(self, doctor, commit=True):
#         return save_object(self, Patient, commit, *self.Meta.exclude, registered_by=doctor)
#
#     def __str__(self):
#         return getValue(self, 'first_name') + getValue(self, 'last_name')
# class CaseForm(forms.ModelForm):
#
#     class Meta:
#         model = Patient
#         exclude = []
#
#     def __str__(self):
#         return 'Case'
#
# class ApptForm(forms.ModelForm):
#     class Meta:
#         model = Appointment
#         exclude = []
#
#     def __str__(self):
#         return 'Appointment'

clinic/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist

from clinic.forms import *
from clinic.models import *
from clinic.utils import log, utilities
<<<<<<< HEAD
=======
from clinic.forms import *
>>>>>>> 5ab21846fc6691c11e626fe83a36c178362f9805

logger = log.Logger()

def get_user(request):
	return Doctor.objects.get(pk=request.session['doctor_id'])

def index(request):
	context, page = {'model_doctor' : Doctor, }, 'index.html'
	if 'doctor_id' in request.session:
		try:
			doctor = get_user(request)
			context['doctor'] = doctor
			if 'clinic_id' in request.session:
				clinic = Clinic.objects.get(pk=request.session['clinic_id'])
				context["clinic_head"] = True
				context['branch'] = clinic.branch_set.get(pk=request.session['branch_id'])
				context['branches'] = list(clinic.branch_set.all())
				context['branches'].remove(context['branch'])
			elif 'branch_id' in request.session:
				context['branch'] = Branch.objects.get(pk=request.session['branch_id'])
		except (ObjectDoesNotExist) as ex:
			logger.w(ex)
			return logout(request)
	else:
		page = "login.html"
		if request.method == 'POST':
			form = LoginForm(request.POST)
			if form.is_valid():
				username = request.POST['username']
				d = Doctor.objects.get(pk=username)
				try:
					clinic = d.clinic
					request.session['clinic_id'] = clinic.pk
					try:
						request.session['branch_id'] = d.branch.pk
					except ObjectDoesNotExist as e:
 						request.session['branch_id'] = clinic.branch_set.all()[0].pk
				except ObjectDoesNotExist as ex:
					try:
						request.session['branch_id'] = d.branch.pk
					except ObjectDoesNotExist as e:
						try:
							request.session['branch_id'] = d.branchassistantdoctor.branch.pk
						except Exception as e:
							# TODO: add_cookie to show error
							context['ermsg'] = "Username '" + username + "' doesn't have branch associated with it contact Database administrative"
							logger.w(e, "Username '" + username + "' doesn't have branch associated with it contact Database administrative")
							return render(request, 'clinic/' + page, context)
				request.session['doctor_id'] = username
				return redirect('/clinic')
			else:
				context['extra'] = {'values' : form.data , 'errors' : dict(form.errors)}
	return render(request, 'clinic/' + page, context)

def logout(request):
	try:
		del request.session['doctor_id']
	except KeyError: pass
	return redirect('/clinic')

def add_patient(request):
	d, clinic = None, None
	try:
		d = get_user(request)
		if 'clinic_id' in request.session:
			clinic = Clinic.objects.get(pk=request.session['clinic_id'])
		elif 'branch_id' in request.session:
			clinic = branch.objects.get(pk=request.session['branch_id']).clinic
		else: clinic = d.branchassistantdoctor.branch.clinic
	except Exception as e:
		logger.e(e, "views.py > add_patinet: Getting Patient Failed");
		raise e
		# return logout(request)
	form = PatientFormSet(request.POST, clinic)
	context = {'doctor' : d, "form" : form.get_form_as_table(), }

	if request.method == "POST":
		if form.is_valid:
			p = form.save()
			return redirect('/clinic/view/patient/' + str(p.pk))
		else:
			context['extra'] = {'data' : None, 'errors' : dict(forms.get_errors()), }
	else:
		pass
	return render(request, 'clinic/new-patient.html', context)

add_functions = {
	'patient' : add_patient
}

def add(request, model):
	return add_functions[model](request)

def view(request, model, pk):
	# TODO: AddView For viewing models
	raise Http404

# models = {'doctor' : Doctor,
# 		  'patient' : Patient,
# 		  'case' : Case,
# 		  'appt' : CaseAppointment, }

#
# def index(request):
# 	d = get_user(request)
# 	logger.d(type(d))
# 	if(isinstance(d, Exception)):
# 		err = 'Session Experied!'
# 		if(isinstance(d, ObjectDoesNotExist)):
# 			err = 'Login Required'
# 		response = redirect('login/');
# 		response.set_cookie('error', err, 5)
# 		return response
# 	return render(request, 'clinic/index.html', {'doctor': d})
#
#

# # def view_object(request, object, pk):
# #     objects = []
# #     try:
# #         doctor = Doctor.objects.get(pk=request.session['current_user'])
# #         context = {'doctor' : doctor, 'pk' : pk, 'obj' : object, }
# #     except Exception as e:
# #         return redirect('/clinic/')
# #     if not object in models.keys():
# #         raise Http404
# #     model = models[object]
# #     if pk == 'all':
# #         objects = list(getattr(doctor, object + '_set').all());
# #     else:
# #         object = get_object_or_404(model, pk=int(pk))
# #         objects.append(object)
# #     context['objects'] = objects
# #     return render(request, 'clinic/view.html', context)
#
# def add_doctor(request):
# 	context = dict()
# 	form = DoctorForm()
# 	if request.method == 'POST':
# 		form = DoctorForm(request.POST)
# 		logger.d.d('Post Data:\n', request.POST)
# 		if form.is_valid():
# 			try:
# 				doctor = form.save()
# 			except Exception as e:
# 				context['extra'] = { 'errors': e.data, 'values' : form.data, }
# 			else:
# 				return redirect('/clinic/')
# 		else:
# 			context['extra'] = {'errors' : dict(form.errors), 'form' : form, 'values' : form.data, }
# 	context['object'] = Doctor
# 	context['address'] = Address
# 	return render(request, 'clinic/new-doctor.html', context)
#
# def add_patient(request):
# 	try:
# 		context = {'doctor' :  Doctor.objects.get(pk=request.session['current_user']) }
# 	except Exception as e:
# 		return redirect('/clinic/')
# 	if request.method == 'POST':
# 		form = PatientForm(request.POST)
# 		if form.is_valid():
# 			try:
# 				patient = form.save(context['doctor_id'])
# 			except Exception as e:
# 				context['extra'] = {'errors': e.data, 'values' : form.data, }
# 			else:
# 				# TODO: add success msg
# 				return redirect('/clinic/')
# 		else:
# 			context['extra'] = {'errors': dict(form.errors), 'form' : form, 'values' : form.data, }
# 	context['object'] = Patient
#
# 	return render(request, 'clinic/new-patient.html', context)
#
# def add_case(request):
# 	p = validate_user(request)
# 	if(p is not None):
# 		return p
#
# create_func = {'doctor' : add_doctor, 'patient': add_patient,
# 				'case' : add_case, }
#
# def add_object(request, object):
# 	if object in create_func.keys():
# 		return create_func[object](request)
# 	raise Http404
# #
# #
# # def handler404(request, *args, **argv):
# #     response = render_to_response('404.html', {}, context_instance=RequestContext(request))
# #     response.status_code = 404
# #     return response

clinic/templates/clinic/includes/footer.html
<footer>
	<div class="container-fluid">
        <!-- <div class="container text-white bg-secondary">
            <div class="col-3 col-sm-12 mx-auto">
                <h5>About us</h5>
                <ul>
                    <li class="">text</li>
                    <li class="">text</li>
                    <li class="">text</li>
                </ul>
            </div>
        </div> -->
        <div id="foot" class="row bg-dark text-muted px-2 text-center">
			<p class="col-12 m-0 p-1">
				© Copyright 2018 Clinic | By Pranav Raut
			</p>
		</div>
	</div>
</footer>

clinic/templates/clinic/includes/header.html
{% load static %}
{% load utilities %}
<nav class="navbar {% if doctor %} navbar-expand-lg {% endif %} navbar-light bg-light sticky-top">
	<a class="navbar-brand" href="{% url 'clinic:index' %}">Clinic</a>
	{% if doctor %}
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbar">
		{% if branch and not clinic_head %}
		<span class="nav-text">Branch: {{ branch.name }}</span>
		{% endif %}
		<ul class="navbar-nav">
			{% if clinic_head %}
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">Branch: {% title branch.name %}</a>
				<div class="dropdown-menu px-2">
					<small class="dropdown-item-text">{{ branch }}</small>
					<div class="dropdown-divider"></div>
					<h6 class="dropdown-header">More Branches</h6>
					{% for b in branches %}
					<a class="dropdown-item rounded" href="#">{% title b %}</a>
					{% endfor %}
					{% if not branches %}
					<small class="dropdown-item-text">None</small>
					{% endif %}
					<div class="dropdown-divider"></div>
					<a class="btn btn-primary w-100 rounded" href="#">Add</a>
				</div>
			</li>
			{% endif %}
		</ul>
		<form class="form-inline mx-auto my-2 my-lg-0" method="put" action="search">
			<div id="search-form" class="input-group">
				<input id="search-bar" class="form-control" type="search" name="q" placeholder="Search here..." >
				<div class="input-group-append dropdown">
					<button class="btn btn-outline-primary" type="submit">Search</button>
					<button class="btn btn-primary dropdown-toggle dropdown-toggle-split "
					type="button" data-toggle="dropdown">
					</button>
					<ul class="dropdown-menu check-form p-2">
						<li><h6 class="dropdown-header">Also Search in</h6></li>
						<li class="form-check justify-content-start">
							<label href="#" class="form-check-label" data-value="address" tabIndex="-1">
								<input class="form-check-input" type="checkbox" name="address" hidden>Addresses
							</label>
						</li>
						<li class="form-check ">
							<label href="#" class="form-check-label" data-value="people" tabIndex="-1">
								<input class="form-check-input" type="checkbox" name="people" hidden>People
							</label>
						</li>
						<li class="form-check justify-content-start">
							<label href="#" class="form-check-label" data-value="drug" tabIndex="-1">
								<input class="form-check-input" type="checkbox" name="drug" hidden>Drugs
							</label>
						</li>
						<li class="form-check justify-content-start">
							<label href="#" class="form-check-label" data-value="disease" tabIndex="-1">
								<input class="form-check-input" type="checkbox" name="disease" hidden>Diseases
							</label>
						</li>
					</ul>
				</div>
			</div>
		</form>
		<ul class="navbar-nav mt-2 mt-lg-0">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
					<img id="profile-img" class="rounded-circle"src="{% static doctor.get_profile_url %}" alt="Profile Icon"/>
					{{ doctor.first_name}}
				</a>
				<div class="dropdown-menu px-2">
		          <a class="dropdown-item rounded" href="#">Profile</a>
		          <a class="dropdown-item rounded" href="#">Stats</a>
		        </div>
	      	</li>
			<li class="nav-item">
				<a href="{% url 'clinic:logout' %}" class="nav-link">Logout</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#help">Help</a>
			</li>
		</ul>
	</div>
	{% else %}
	<ul class="navbar-nav mt-2 mt-lg-0 justify-content-end">
		<li class="nav-item">
			<a class="nav-link" href="#help">Help</a>
		</li>
	</ul>
	{% endif %}
</nav>